### ISSUE TITLE
Can't find _brand.scss 

### ISSUE THREAD

**Issue by ThibautLucas** [app-generator/django-dashboard-black#1]
Hi, 

I would like to change the brand color but I can't find the **_brand.scss** file. 

I tried changing the **_variables.scss** and recompiling scss with gulp but it doesn't seem to change colors.

**Comment by app-generator** [comment]
Hello @ThibautLucas, 

Thank you for using something provided by AppSeed.
The file you mention `_brand.scss` is not provided by the UI Kit Vendor. Just search manually the RAW HTML project used in our automated workflow. 

Try to open an issue on the original HTML version
https://github.com/creativetimofficial/black-dashboard

Sorry to point you to Creative-Tim, but is not something that we can help with. 
I will close the issue. Feel free to ping us if you get the file. 

- Ty
