### ISSUE TITLE
Can I use any dashboard for Django CMS 

### ISSUE THREAD

**Issue by khaldon** [app-generator/django-dashboard-black#2]
I am creating app using Django cms Is possible to use your dashboard integrated with Django CMS ?

**Comment by app-generator** [comment]
Hello @khaldon, 

You're asking if is allowed to use the dashboard in your project or if the dashboard is ready to be used in Django CMS.
I will answer both questions below:

- You can use this dashboard and also [others](https://github.com/app-generator/admin-dashboards) released un the [MIT license](https://github.com/app-generator/license-mit) in any project you want

- Django CMS integration/use - this is not tested or even planned. Feel free to make your tests and let us know the results. 

For a LIVE chat and assistance, feel free to join the [Discord](https://discord.gg/fZC6hup) community.
I will close this issue.
