### ISSUE TITLE
Can't not reach any urls for new app

### ISSUE THREAD

**Issue by redcican** [app-generator/django-dashboard-black#3]
Hello,

I am trying to create my own app inside the project, but the URLs reverse doesn't work. 
For example, I created an app call user_profile, and I want to change the User Profile when the user clicks the "Profile" button.

` <li class="nav-link"><a href="{% url 'profile' %}" class="nav-item dropdown-item">Profile</a></li>`  # navigattion.html

However, only inside your original "app" folder, this button will work, for any other new apps, it won't work. 
Is this only possible for Pro Version? 

`path('user-profile/', include("user_profile.urls")) # core.urls for new app user_profile`

`urlpatterns = [
    path('profile', views.user_profile_view, name='profile')
] # urls for user_profile`

views 
```
@login_required
def user_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False
    if form.is_valid():
        form.save()
        confirm = True
    context = {
        'profile': profile,
        'form': form,
        'confirm': confirm,
    }

    return render(request, 'user_profile/profile.html', context) 
```
I create a folder called user_profile inside templates,
thank you so much.

**Comment by app-generator** [comment]
Hello @redcican, 

Thank you for using our products. 
As a solution, try to update `core/urls.py` as suggested below. Django will resolve the routing by scanning your app first. 

```python
urlpatterns = [
    path('admin/', admin.site.urls),              # Django admin route
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("user_profile.urls"))      # <---------------------------------- NEW APP HERE
    path("", include("app.urls"))                   # UI Kits Html files
]
```

Let us know your progress.

**Comment by redcican** [comment]
Hello @app-generator , thanks, it works. But why? the new app's urls must be defined before app.urls?

And I have another question about media. 

here is my settings.py for media and static:

`STATIC_ROOT = CORE_DIR / 'static'
STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = 'media' `

and I also add it to urls: 
`urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)`

But when I upload the image to the backend, it can resolve an URL like: 
`http://127.0.0.1:8000/media/avatars/profil.jpg`, but the page is still not found. what did I miss?

**Comment by app-generator** [comment]
Hello @redcican, 

Django routing system .. must be fast. 
The first rule that matches the request is used, without scanning all definitions. 

Regarding the media settings, we don't have a working sample to provide. 
At first look, your settings look good. 

We noted this `use case` and soon will be added to the documentation.
Let us know your progress.

**Comment by app-generator** [comment]
Hello @redcican, 
Please re-test the issue using the latest release.
Closing.
