### ISSUE TITLE
How to make light mode and sidebar color persist

### ISSUE THREAD

**Issue by devqueue** [app-generator/django-dashboard-black#5]
I have searched everywhere and i can't find a way to make the light mode or the color of the side bar remain after the refresh. Can someone please help

**Comment by app-generator** [comment]
Hello @devqueue 

Sorry for this delay. somehow the notification landed in spam. 

To hardcode the `white`  you need to apply `white-content` class to the body element (see the enclosed image) 

Let us know your progress.

![image](https://user-images.githubusercontent.com/51070104/159409496-b0c0b06c-71ab-45cc-86b1-39de114eff36.png)

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
